# -*- coding: utf-8 -*-
"""support_vector_mechine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RPPnlcvMmS87gDz6p_KbTd_XGjwLeR-U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as mtp
#from sklearn import preprocessing
dataset=pd.read_csv('suv_data.csv')
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values


from sklearn.model_selection import train_test_split
#feature scalling
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(y_test,y_pred))